Vinzent03/obsidian-git

.gitignore
main.ts

`{{files}}` will be replaced with `A file1 file2, D file2 file3` where A/D means the status of file in git.

add {{files}} template placeholder

---

main.ts

When setting is enabled, the remote repo will be pulled at the start of each backup session, to enable the local repo to stay in sync with remote changes.
This feature is specially useful when the remote repo is being frequently updated (e.g. when using a mobile app such as gitJournal to update documents from your phone). In these cases, currently, the local repo cannot be pushed until a manual pull is performed.

feat: add setting for auto-pull on backup

---

main.ts

I have a pre-push hook that ask for user confirmation. Sadly it makes obsidian-git push failed by timeout since I cannot make tty input.
A simple solution is to add an environment variable when spawn git process, check it in the hook and bypass the confirmation.
I also think configurable push command will be cool, but it's too much for this case.

feat: add env var OBSIDIAN_GIT for scripting

---

main.ts

Some git configurations will return ascii color codes when using the `simpleGit` command `branchLocal()`. This pr changes the `branchLocal()` call to `branch(['--no-color']). 
When `simpleGit.branch([options])` is called with at least one argument, it will only list local branches: https://github.com/steveukx/git-js/blob/0685a8b5d8558252bb50451d9c6c8b2bd474d0c8/src/lib/tasks/branch.ts#L18
```js
BranchSummaryResult {
all: [ '\x1B[32mmaster\x1B[m' ],
branches: {
'\x1B[32mmaster\x1B[m': {
current: true,
name: '\x1B[32mmaster\x1B[m',
commit: 'e686844',
label: 'init commit'
}
},
current: '\x1B[32mmaster\x1B[m',
detached: false
}
```
```js
BranchSummaryResult {
all: [ 'master' ],
branches: {
master: {
current: true,
name: 'master',
commit: 'e686844',
label: 'init commit'
}
},
current: 'master', …
```

FIX: Changed the branchLocal command to branch with no-color

---

src/constants.ts
src/main.ts
src/settings.ts
src/simpleGit.ts
src/types.ts

I use both obsidian-sync and obsidian-git so I can have both live updates & mobile support (via obsidian-sync) while also having change-by-change history (via obsidian-git).  While far from home over the holidays with my work laptop, I encountered more than a few merge conflicts due to a race condition in which my laptop at home dutifully received changes via obsidian-sync, committed them, and then while it attempted to push those changes, it discovered that my work laptop had already committed changes and was thus in a conflict.
What this does is add a third method for handling sync (in addition to the existing `rebase` and `merge` methods) that just lazily updates the current `HEAD` to match the sha of any fetched remote data *without updating the local filesystem*.  That might seem …

Add new 'Sync Method' setting in place of `mergeOnPull` and new experimental obsidian-sync compatible sync method.

---

src/constants.ts
src/gitManager.ts
src/settings.ts
src/simpleGit.ts
src/types.ts

For my use case, I wanted to have a public blog live within my obsidian vault. This blog is hosted and built on github pages and is a normal git repository. To keep things separated, the git repository be in a subfolder not at the root of the vault. This is unsupported currently and referenced in a few issues:
* https://github.com/denolehov/obsidian-git/issues/11 
* https://github.com/denolehov/obsidian-git/issues/169
A setting was added called bath path that allows users to set a custom git root. This is then used by `simple-git` when configuring the SimpleGit RepoManger. 
A user is only allowed on repo in the entire vault. I evaluated having multiple git repo support but it turned out to be a larger refactor than I had time for. For my use case this is totally fine. 
Thanks for the …

feat: custom git repository root

---

src/simpleGit.ts

fix recusrive submods

---

src/gitManager.ts
src/main.ts
src/simpleGit.ts
src/types.ts
src/ui/sidebar/components/pulledFileComponent.svelte
src/ui/sidebar/components/treeComponent.svelte
src/ui/sidebar/gitView.svelte

This PR implements #260
Each time the user pulls at least one file, the list of pulled files will be shown in the new section. After app restart, this list will be empty as we are not storing any history.
TreeView:
DefaultView:

Implement `Recently Pulled Files` section

---

src/settings.ts

For some reason, I wasn't able to run this locally so I had to do it on GitHub itself, I hope my changes in the settings make sense. 
I was confused by the setting for auto backups for file changes, because of that I added a name and changed the description so it should be clear. 
Does something happen when the toggle is `off` if not, then the "If turned off, ..." was redundant anyway?! 
If you need anything else, let me know. Great plugin by the way. 🙌🏼

Update Description for Auto Backup-Toggle

---

src/isomorphicGit.ts

Further fix for #292 
There was a fix made in commit `7d6252795ca62f4176fee90d674041659a0a1d9f`, however, this introduced a bug where "progressNotice" could be undefined, and the progress function was attempting to set a property on this undefined object. This would throw an error, and many git operations could not be performed.
I simply wrapped the progressNotice in an if statement to check if it was defined - without tests I am not sure if there are side effects, but this might work.

Fix bug in hiding mobile notifications

---

src/main.ts

Messaged read `Pulled 0 file from remote` etc, changed to `Pulled 0 files from remote`. 
Additionally, changed `You have 1 conflict file` to `You have conflicts in 1 file` or `You have conflicts in 5 files` for the case with more than 1 file.

Changed message grammar to use 0 files instead of 0 file

---

src/settings.ts
src/simpleGit.ts
src/types.ts

This commit allows users to automatically checkout the same branch in submodules (if present) as the root repository. This does not create any branches.
Additional refactor for retrieval of submodule paths to allow code reuse.
Additional question: we've noticed that the "tabs" indent_style setting in the .editorconfig does not match the indentation used in the code (being spaces). Which one of the two should it be?
(co-authored by @yentlprojects)

Adds option to recursively checkout submodules

---

src/isomorphicGit.ts
src/main.ts
src/simpleGit.ts
src/utils.ts

This fixes handling of branches that contain `/` in their names.

Fix splitting remote branch name

---

src/openInGitHub.ts

Added error handlings when a remote branch is not configured.
Although I could not imagine a case where a remote branch name could be retrieved but not the current branch name, it could occur based on the types, so I also added.

Add error handlings when retrieving branch names

---

src/main.ts

Resolving merge conflicts is pretty hard on mobile (#340) and though some workarounds exist, the workflow is not ideal, especially if you don't have access to your desktop. 
I think a quick solution would be to provide a `git reset --hard` command to allow mobile users to discard all their local changes to the last commit. They can then pull without conflicts and re-add their changes manually.
This PR adds a "Reset hard" command using the `gitManager`'s `discardAll` method
**Update:** I realized after an embarrassingly long amount of time that you can use the source control view to achieve the same effect, However I still think there's value in this command considering how common an operation this could be from the discussion in #340

Add discard all changes command

---

src/isomorphicGit.ts

Fixes #429
This issue is caused by a `NotFoundError` that may occur when executing `readBlob`. The solution here is to catch the error and return `undefined` when that error occurs.
~~In addition I have simplified the logic by removing the `stagedChanged` argument and removing the branching by `stagedChanged`. In the end, all we want to see in the diff view is the difference from `HEAD`, so I think this is sufficient.~~

Fix diff view issue on smartphones and tablets

---

tsconfig.json

Currently, the codemirror type definition file is causing compile errors and CI is failing. As an emergency workaround, I have enabled `skipLibCheck`.

Enable `skipLibCheck` to fix CI

---

src/gitManager/gitManager.ts
src/gitManager/isomorphicGit.ts
src/gitManager/myAdapter.ts
src/gitManager/simpleGit.ts
src/main.ts
src/openInGitHub.ts
src/settings.ts
src/ui/history/historyView.svelte
src/ui/sourceControl/components/fileComponent.svelte
src/ui/sourceControl/components/stagedFileComponent.svelte

To group related classes together and improve readability, I moved GitManager, its child classes, and MyAdapter, which is used inside the IsomorphicGit class, under `gitManager/`.

Organize GitManager-related classes

---

src/main.ts

Remove the `@ts-ignore` annotation as it is unnecessary under the current configuration.

Remove `@ts-ignore` annotation in `main.ts`

---

src/setting/settings.ts

make visible `{{files}}` variable in settings
so also non-developers (or persons without having to read the code) could use it.
Personaly I was reading the code to add this feature but it turned out it's already there, just was not mentionend :D 
I find it very useful;)

make visible (secret/hidden?) `{{files}}` variable in settings

---

src/gitManager/isomorphicGit.ts

From the table of all possible combinations in https://isomorphic-git.org/docs/en/statusMatrix.

fix: missing git file status 113

---

.github/workflows/releases.yml

Hi,
Update release template to use softprops/action-gh-release as actions/create-release is deprecated with release notes generations.
1. Update the release workflow from actions/create-release to softprops/action-gh-release, as former is deprecated by now.
2. Add release notes auto generation during release creation, example: https://github.com/peterzhu1992/obsidian-git/releases/tag/1.0.6-test
3. Simplify the tag name retrieval and remove the deprecated set-output.
Thanks.

Update release template to use softprops/action-gh-release with release notes generations

---

docs/Tips-and-Tricks.md

I noticed this file was generated since I use obsidian on my iPhone, so it should probably be ignored too if you don't want workspace data.

Adds .obsidian/workspace-mobile.json to ignore.

---

.eslintrc
src/main.ts
src/ui/sourceControl/components/stagedFileComponent.svelte
tsconfig.json

To fix the CI errors, I mainly updated the svelte config in `.eslintrc`.
See comments for other fixes and additional information.

Fix CI errors

---

src/main.ts

Since the return type of `this.loadLastAuto()` is non-promise, these awaits are redundant. So this pull request removes them.

Remove redundant awaits

---

src/setting/settings.ts

Grammatical improvement in settings.
Under miscellaneous, changed "Show changes files count in status bar" to "Show the count of modified files in the status bar"

fix: grammar improvement in settings

---

src/gitManager/isomorphicGit.ts
src/main.ts
src/setting/localStorageSettings.ts

Refactors `getConflict()` and `setConflict()` to use boolean values instead of strings, similar to `getPluginDisabled()` and `setPluginDisabled()`.

refactor: Use boolean values for `getConflict()` and `setConflict()`

---

src/setting/settings.ts
src/utils.ts

What my changes do:
- add `formatMinutes` function
- use "minute" when autoSaveInterval is 1
- else use "minutes"
- Prevents the scenario phrase "1 minutes."
- Improve grammar for `autoBackupAfterFileChange` plugin
- turn message into multiline string for easier readability in code
I did think about omitting the interval value if it's set to 1 i.e.:
- "Every minute."
- "Every x minutes."
But I believe being more explicit with whatever interval value the user has set reinforces the idea that the application has registered their input.

fix: update settings grammar

---

src/constants.ts
src/main.ts
src/setting/settings.ts
src/types.ts

When notifications aren't disabled this new setting will be displayed. Enabling this setting, will prevent the "No changes to push" and "No changes to commit" messages from displaying. This doesn't prevent
these notifications from appearing in the status bar.
Adds feature to resolve #675

Added setting to disable 'No changes...' popups

---

styles.css

Change to prevent git blame gutter from superposing text in smaller screens. There is no change for screens larger than 1000px
Before:
After:
Before and After for larger screens:

Prevent text superposing git blame

---

src/gitManager/simpleGit.ts

Re-sending this PR:
https://github.com/denolehov/obsidian-git/pull/587
Apologies for resubmission, I had to refactor my fork and the branch tracked by the old PR. Shouldn't happen again

fix: Adjust git.cwd to use a relative path to git root

---

src/gitManager/gitManager.ts
src/gitManager/simpleGit.ts

This fixes #660.
Currently, `getRelativeRepoPath` considers only the case of git repository is located inside the vault.
If the vault is inside a subdirectory of git repository (this is a common case when you are using a self-host publishing system like [Quartz](https://github.com/jackyzha0/quartz)), line authoring feature won't work.
This code resolves the relative path between git repo and vault using `path` library.

fix: getRelativeRepoPath for the case of vault-inside-repo

---

src/ui/history/historyView.ts
src/ui/sourceControl/components/pulledFileComponent.svelte
src/ui/sourceControl/sourceControl.ts

Remove some `@ts-ignore` comments that are not suppressing any type errors currently.

chore: Remove unnecessary `@ts-ignore`

---

src/commands.ts

Everywhere else in the commands and the docs do you use `.gitignore` except for this one command. Just making it consistent.

fix: Make the spelling of .gitignore consistent

---

src/ui/diff/splitDiffView.ts

Closes #857  Handles only the "nested repository" case, could be expanded to handle all errors.

Fix diff view bug 

---

src/types.ts
src/ui/history/components/logFileComponent.svelte
src/ui/sourceControl/components/fileComponent.svelte
src/ui/sourceControl/components/stagedFileComponent.svelte
src/utils.ts

Closes #883 
Gracefully handles the case where the internal API function isn't available anymore.

fix: improve the "is file openable in obsidian" check

---

src/lineAuthor/view/gutter/gutter.ts

This bug has been here since the very beginning when I implemented the line authoring into obsidian-git.
For unknown reasons, somtimes the `dom.remove()` fails and an exception is bubbled up - which makes the line authoring and afaik the whole plugin crash. Then the line authoring suddenly disappears and can't be brought back without a restart. It's hard to consistently reproduce it and I didn't brother too much with it back then - but this simply try and catch should fix it sufficiently.
Whenever I come across this error, I have to restart obsidian - but this isn't a good workaround for users who don't know what's happening. They'll probably just abandon this plugin or whatever.
Do you have any questions?

fix: line authoring crashes when dom Element cannot be removed.

---

src/ui/diff/splitDiffView.ts
styles.css

Closes #881 
And believe me, the original styling of the indicator was even uglier.

feat: collapse unchanged lines in split diff view
